classdef Convt < dagnn.Layer
  properties
    size = [0 0 0 0]
    hasBias = true
    upsample = [1 1]
    crop = [0 0 0 0]
    numgroups = 1
    opts = {'cuDNN'}
  end

  methods
    % ---------------------------------------------------------------------
    function outputs = forward(obj, inputs, params)
      if obj.hasBias
        outputs{1} = vl_nnconvt(...
          inputs{1}, params{1}, params{2}, ...
          'upsample', obj.upsample, ...
          'crop', obj.crop, ...
          'numgroups', obj.numgroups, ...
          obj.opts{:}) ;
      else
        outputs{1} = vl_nnconvt(...
          inputs{1}, params{1}, [], ...
          'upsample', obj.upsample, ...
          'crop', obj.crop, ...
          'numgroups', obj.numgroups, ...
          obj.opts{:}) ;
      end
    end

    function [derInputs, derParams] = backward(obj, inputs, params, derOutputs)
      if obj.hasBias
        [derInputs{1}, derParams{1}, derParams{2}] = vl_nnconvt(...
          inputs{1}, params{1}, params{2}, derOutputs{1}, ...
          'upsample', obj.upsample, ...
          'crop', obj.crop, ...
          'numgroups', obj.numgroups, ...
          obj.opts{:}) ;
      else
        [derInputs{1}, derParams{1}] = vl_nnconvt(...
          inputs{1}, params{1}, [], derOutputs{1}, ...
          'upsample', obj.upsample, ...
          'crop', obj.crop, ...
          'numgroups', obj.numgroups, ...
          obj.opts{:}) ;
      end
    end

    % ---------------------------------------------------------------------
    function params = init(obj)
      error('init function not implemented') ;
    end

    function obj = Convt(varargin)
      obj.load(varargin) ;
    end

  end
end
