function net = cnn_imagenet_init(varargin)
% CNN_IMAGENET_INIT  Baseline CNN model

opts.scale = 1 ;
opts.initBias = 0.1 ;
opts.weightDecay = 1 ;
opts = vl_argparse(opts, varargin) ;

net.layers = {} ;

% Block 1
net.layers{end+1} = struct('type', 'conv', 'name', 'conv1', ...
                           'filters', 0.01/opts.scale * randn(11, 11, 3, 96, 'single'), ...
                           'biases', zeros(1, 96, 'single'), ...
                           'stride', 4, ...
                           'pad', 0, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu1') ;
net.layers{end+1} = struct('type', 'pool', 'name', 'pool1',  ...
                           'method', 'max', ...
                           'pool', [3 3], ...
                           'stride', 2, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'normalize', ...
                           'param', [5 1 0.0001/5 0.75]) ;

% Block 2
net.layers{end+1} = struct('type', 'conv', 'name', 'conv2', ...
                           'filters', 0.01/opts.scale * randn(5, 5, 48, 256, 'single'), ...
                           'biases', opts.initBias*ones(1, 256, 'single'), ...
                           'stride', 1, ...
                           'pad', 2, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu2') ;
net.layers{end+1} = struct('type', 'pool', 'name', 'pool2', ...
                           'method', 'max', ...
                           'pool', [3 3], ...
                           'stride', 2, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'normalize', 'name', 'norm2', ...
                           'param', [5 1 0.0001/5 0.75]) ;

% Block 3
net.layers{end+1} = struct('type', 'conv', 'name', 'conv3', ...
                           'filters', 0.01/opts.scale * randn(3,3,256,384,'single'), ...
                           'biases', opts.initBias*ones(1,384,'single'), ...
                           'stride', 1, ...
                           'pad', 1, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu3') ;

% Block 4
net.layers{end+1} = struct('type', 'conv', 'name', 'conv4', ...
                           'filters', 0.01/opts.scale * randn(3,3,192,384,'single'), ...
                           'biases', opts.initBias*ones(1,384,'single'), ...
                           'stride', 1, ...
                           'pad', 1, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu4') ;

% Block 5
net.layers{end+1} = struct('type', 'conv', 'name', 'conv5', ...
                           'filters', 0.01/opts.scale * randn(3,3,192,256,'single'), ...
                           'biases', opts.initBias*ones(1,256,'single'), ...
                           'stride', 1, ...
                           'pad', 1, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu5') ;
net.layers{end+1} = struct('type', 'pool', 'name', 'pool5', ...
                           'method', 'max', ...
                           'pool', [3 3], ...
                           'stride', 2, ...
                           'pad', 0) ;

% Block 6
net.layers{end+1} = struct('type', 'conv', 'name', 'fc6', ...
                           'filters', 0.01/opts.scale * randn(6,6,256,4096,'single'),...
                           'biases', opts.initBias*ones(1,4096,'single'), ...
                           'stride', 1, ...
                           'pad', 0, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu6') ;
net.layers{end+1} = struct('type', 'dropout', ...
                           'rate', 0.5) ;

% Block 7
net.layers{end+1} = struct('type', 'conv', 'name', 'fc7', ...
                           'filters', 0.01/opts.scale * randn(1,1,4096,4096,'single'),...
                           'biases', opts.initBias*ones(1,4096,'single'), ...
                           'stride', 1, ...
                           'pad', 0, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;
net.layers{end+1} = struct('type', 'relu', 'name', 'relu7') ;
net.layers{end+1} = struct('type', 'dropout', ...
                           'rate', 0.5) ;

% Block 8
net.layers{end+1} = struct('type', 'conv', 'name', 'fc8', ...
                           'filters', 0.01/opts.scale * randn(1,1,4096,1000,'single'), ...
                           'biases', zeros(1, 1000, 'single'), ...
                           'stride', 1, ...
                           'pad', 0, ...
                           'filtersLearningRate', 1, ...
                           'biasesLearningRate', 2, ...
                           'filtersWeightDecay', opts.weightDecay, ...
                           'biasesWeightDecay', 0) ;

% Block 9
net.layers{end+1} = struct('type', 'softmaxloss', 'name', 'loss') ;

% Other details
net.normalization.imageSize = [227, 227, 3] ;
net.normalization.interpolation = 'bicubic' ;
net.normalization.border = 256 - net.normalization.imageSize(1:2) ;
net.normalization.averageImage = [] ;
net.normalization.keepAspect = true ;
