%%
vl_compilenn('enableGpu', true, ...
               'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0', ...
               'cudaMethod', 'nvcc', ...
               'enableCudnn', 'true', ...
               'cudnnRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0', ...
               'EnableCudnn', true, ...
               'CudnnRoot', 'D:\VLFEAT\matconvnet\cudnn', ...
               'Verbose', 0) ;